"""Hand joint naming conventions for OpenEgo dataset."""

MANO_JOINT_NAMES = ["wrist", 
                    "thumb_cmc", "thumb_mcp", "thumb_pip", "thumb_tip", 
                    "index_mcp", "index_pip", "index_dip", "index_tip", 
                    "middle_mcp", "middle_pip", "middle_dip", "middle_tip", 
                    "ring_mcp", "ring_pip", "ring_dip", "ring_tip", 
                    "little_mcp", "little_pip", "little_dip", "little_tip"]

# Subset of EGODEX joint mappings needed for OpenEgo
EGODEX_JOINT_NAMES = {
    "leftArm": "left_wrist",
    "leftIndexFingerIntermediateBase": "left_index_dip",
    "leftIndexFingerKnuckle": "left_index_pip",
    "leftIndexFingerMetacarpal": "left_index_mcp",
    "leftIndexFingerTip": "left_index_tip",
    "leftLittleFingerIntermediateBase": "left_little_dip",
    "leftLittleFingerKnuckle": "left_little_pip",
    "leftLittleFingerMetacarpal": "left_little_mcp",
    "leftLittleFingerTip": "left_little_tip",
    "leftMiddleFingerIntermediateBase": "left_middle_dip",
    "leftMiddleFingerIntermediateTip": "left_middle_IntermediateTip",
    "leftMiddleFingerKnuckle": "left_middle_pip",
    "leftMiddleFingerMetacarpal": "left_middle_mcp",
    "leftMiddleFingerTip": "left_middle_tip",
    "leftRingFingerIntermediateBase": "left_ring_dip",
    "leftRingFingerIntermediateTip": "left_ring_IntermediateTip",
    "leftRingFingerKnuckle": "left_ring_pip",
    "leftRingFingerMetacarpal": "left_ring_mcp",
    "leftRingFingerTip": "left_ring_tip",
    "leftThumbIntermediateBase": "left_thumb_mcp",
    "leftThumbIntermediateTip": "left_thumb_pip",
    "leftThumbKnuckle": "left_thumb_cmc",
    "leftThumbTip": "left_thumb_tip",
    "rightHand": "right_wrist",
    "rightIndexFingerIntermediateBase": "right_index_dip",
    "rightIndexFingerIntermediateTip": "right_index_IntermediateTip",
    "rightIndexFingerKnuckle": "right_index_pip",
    "rightIndexFingerMetacarpal": "right_index_mcp",
    "rightIndexFingerTip": "right_index_tip",
    "rightLittleFingerIntermediateBase": "right_little_dip",
    "rightLittleFingerIntermediateTip": "right_little_IntermediateTip",
    "rightLittleFingerKnuckle": "right_little_pip",
    "rightLittleFingerMetacarpal": "right_little_mcp",
    "rightLittleFingerTip": "right_little_tip",
    "rightMiddleFingerIntermediateBase": "right_middle_dip",
    "rightMiddleFingerIntermediateTip": "right_middle_IntermediateTip",
    "rightMiddleFingerKnuckle": "right_middle_pip",
    "rightMiddleFingerMetacarpal": "right_middle_mcp",
    "rightMiddleFingerTip": "right_middle_tip",
    "rightRingFingerIntermediateBase": "right_ring_dip",
    "rightRingFingerIntermediateTip": "right_ring_IntermediateTip",
    "rightRingFingerKnuckle": "right_ring_pip",
    "rightRingFingerMetacarpal": "right_ring_mcp",
    "rightRingFingerTip": "right_ring_tip",
    "rightThumbIntermediateBase": "right_thumb_mcp",
    "rightThumbIntermediateTip": "right_thumb_pip",
    "rightThumbKnuckle": "right_thumb_cmc",
    "rightThumbTip": "right_thumb_tip"
}
